//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public int Passenger_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int Day { get; set; }
        public string Month { get; set; }
        public int Passengers { get; set; }
    }
}
