//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_Reservation_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Registration
    {
        public int User_Id { get; set; }
       
        [DisplayName("First Name")]
        [Required(ErrorMessage = "This field is empty")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This field is empty")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "This field is empty")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This field is empty")]
        [DataType(DataType.Password)]
        [DisplayName("Conform Password")]
        [Compare("Password")]
        public string ConformPassword { get; set; }


        [Required(ErrorMessage = "This field is empty")]
        public string CNIC { get; set; }
    }
}
