//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TicketId { get; set; }
        public string Shedule { get; set; }
        public string Fare { get; set; }
        public string Timing { get; set; }
        public int Seat { get; set; }
    }
}
